// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4VA0iLwwfHvqQaaLcSQfVMkjX4ErmidM',
    appId: '1:649867034699:web:b07adba812f8b181504dce',
    messagingSenderId: '649867034699',
    projectId: 'schedly-app-mobile2',
    authDomain: 'schedly-app-mobile2.firebaseapp.com',
    storageBucket: 'schedly-app-mobile2.firebasestorage.app',
    measurementId: 'G-FNKWN1Q6YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhKhdg3KFCY4ZvXRgdRza2CBhbg42qHFU',
    appId: '1:649867034699:android:eedd2dfcbbbd97c9504dce',
    messagingSenderId: '649867034699',
    projectId: 'schedly-app-mobile2',
    storageBucket: 'schedly-app-mobile2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvP15Rkyo6-m6QcPqAr9ZXGCMjJGu8Dk4',
    appId: '1:649867034699:ios:1572728e70c29d8c504dce',
    messagingSenderId: '649867034699',
    projectId: 'schedly-app-mobile2',
    storageBucket: 'schedly-app-mobile2.firebasestorage.app',
    iosBundleId: 'com.example.flutterAtividadeParcial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvP15Rkyo6-m6QcPqAr9ZXGCMjJGu8Dk4',
    appId: '1:649867034699:ios:1572728e70c29d8c504dce',
    messagingSenderId: '649867034699',
    projectId: 'schedly-app-mobile2',
    storageBucket: 'schedly-app-mobile2.firebasestorage.app',
    iosBundleId: 'com.example.flutterAtividadeParcial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4VA0iLwwfHvqQaaLcSQfVMkjX4ErmidM',
    appId: '1:649867034699:web:4db8ed35bb30f06c504dce',
    messagingSenderId: '649867034699',
    projectId: 'schedly-app-mobile2',
    authDomain: 'schedly-app-mobile2.firebaseapp.com',
    storageBucket: 'schedly-app-mobile2.firebasestorage.app',
    measurementId: 'G-5YNW91SRD9',
  );
}
